"""Add send_count column to emails table

Revision ID: 903c8c1991f9
Revises: a2572967abb1
Create Date: 2026-02-03 07:46:06.477764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903c8c1991f9'
down_revision: Union[str, Sequence[str], None] = 'a2572967abb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('send_count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'send_count')
    # ### end Alembic commands ###
