"""create core tables

Revision ID: a2572967abb1
Revises: e1fd93358d44
Create Date: 2026-02-02 12:00:06.156339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2572967abb1'
down_revision: Union[str, Sequence[str], None] = 'e1fd93358d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmail_message_id', sa.String(length=128), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=128), nullable=True),
    sa.Column('to', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_source', sa.String(length=16), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_white_minutes', sa.Integer(), nullable=False),
    sa.Column('t_blue_minutes', sa.Integer(), nullable=False),
    sa.Column('t_yellow_minutes', sa.Integer(), nullable=False),
    sa.Column('t_red_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=True),
    sa.Column('body_text_template', sa.Text(), nullable=True),
    sa.Column('body_html_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_placeholders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_placeholders')
    op.drop_table('email_attachments')
    op.drop_table('templates')
    op.drop_table('settings')
    op.drop_table('emails')
    # ### end Alembic commands ###
